### ISSUE TITLE
error on watch

### ISSUE THREAD

**Issue by geraldodev** [bassjacob/bstr#2]
Hi,

I get the following error on npm run watch
```
> bstr-demo@1.0.0 watch /home/geraldo/bstr-demo
> bstr watch

{ Error: spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb',
  path: '/home/geraldo/bstr-demo/node_modules/.bin/bsb',
  spawnargs: [ '-clean-world' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bstr-demo@1.0.0 watch: `bstr watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bstr-demo@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geraldo/.npm/_logs/2017-06-19T13_25_18_899Z-debug.log

```
node 8.1.2
npm 5.0.3
Ubuntu 16.04

**Comment by bassjacob** [comment]
Hi @geraldodev,

Can you let me know the output of `ls node_modules`? and can you please try run `npm install` again from inside your bstr-demo folder?

Thanks 😄

**Comment by geraldodev** [comment]
➜  bstr-demo npm install
npm WARN bstr@0.0.4 requires a peer of bs-express@buckletypes/bs-express but none was installed.
npm WARN bstr@0.0.4 requires a peer of bs-json@buckletypes/bs-json but none was installed.
npm WARN bstr@0.0.4 requires a peer of bs-platform@1.7.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of express@^4.15.2 but none was installed.
npm WARN bstr@0.0.4 requires a peer of nodemon@^1.11.0 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react@^15.5.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-dom@^15.5.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-hot-loader@next but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-router@^4.1.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-router-dom@^4.1.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of reason-react@reasonml/reason-react but none was installed.
npm WARN bstr@0.0.4 requires a peer of webpack@^2.5.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of webpack-dev-server@^2.4.5 but none was installed.
npm WARN bstr-demo@1.0.0 No description
npm WARN bstr-demo@1.0.0 No repository field.

and node_modules
node_modules ls -1
```
ansi-regex
bstr
builtin-modules
camelcase
cliui
code-point-at
cross-spawn
decamelize
error-ex
execa
find-up
get-caller-file
get-stream
graceful-fs
hosted-git-info
invert-kv
is-arrayish
is-builtin-module
isexe
is-fullwidth-code-point
is-stream
lcid
load-json-file
locate-path
lru-cache
mem
mimic-fn
normalize-package-data
npm-run-path
number-is-nan
object-assign
os-locale
parse-json
path-exists
path-key
path-type
p-finally
pify
pinkie
pinkie-promise
p-limit
p-locate
pseudomap
read-pkg
read-pkg-up
require-directory
require-main-filename
semver
set-blocking
signal-exit
spdx-correct
spdx-expression-parse
spdx-license-ids
string-width
strip-ansi
strip-bom
strip-eof
validate-npm-package-license
which
which-module
wrap-ansi
y18n
yallist
yargs
yargs-parser
```

**Comment by geraldodev** [comment]
Log
``'
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle bstr-demo@1.0.0~prewatch: bstr-demo@1.0.0
6 silly lifecycle bstr-demo@1.0.0~prewatch: no script for prewatch, continuing
7 info lifecycle bstr-demo@1.0.0~watch: bstr-demo@1.0.0
8 verbose lifecycle bstr-demo@1.0.0~watch: unsafe-perm in lifecycle true
9 verbose lifecycle bstr-demo@1.0.0~watch: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/geraldo/bstr-demo/node_modules/.bin:/home/geraldo/bin:/usr/local/bin:/home/geraldo/.opam/4.02.3+buckle-master/bin:/home/geraldo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle bstr-demo@1.0.0~watch: CWD: /home/geraldo/bstr-demo
11 silly lifecycle bstr-demo@1.0.0~watch: Args: [ '-c', 'bstr watch' ]
12 silly lifecycle bstr-demo@1.0.0~watch: Returned: code: 1  signal: null
13 info lifecycle bstr-demo@1.0.0~watch: Failed to exec watch script
14 verbose stack Error: bstr-demo@1.0.0 watch: `bstr watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid bstr-demo@1.0.0
16 verbose cwd /home/geraldo/bstr-demo
17 verbose Linux 4.4.0-79-generic
18 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error bstr-demo@1.0.0 watch: `bstr watch`
23 error Exit status 1
24 error Failed at the bstr-demo@1.0.0 watch script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by bassjacob** [comment]
So I think this might have been my mistake. Can you verify whether running `npm i` and then `npm run watch` fixes it?

If it doesn't, can you let me know whether your code is available online for me to look at?

**Comment by geraldodev** [comment]
removed the directory and repeated the steps of the home page.
Output of npm i
```
 ✘ geraldo@geraldo-lin  ~/bstr-demo  npm install
npm WARN bstr@0.0.4 requires a peer of bs-express@buckletypes/bs-express but none was installed.
npm WARN bstr@0.0.4 requires a peer of bs-json@buckletypes/bs-json but none was installed.
npm WARN bstr@0.0.4 requires a peer of bs-platform@1.7.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of express@^4.15.2 but none was installed.
npm WARN bstr@0.0.4 requires a peer of nodemon@^1.11.0 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react@^15.5.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-dom@^15.5.4 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-hot-loader@next but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-router@^4.1.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of react-router-dom@^4.1.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of reason-react@reasonml/reason-react but none was installed.
npm WARN bstr@0.0.4 requires a peer of webpack@^2.5.1 but none was installed.
npm WARN bstr@0.0.4 requires a peer of webpack-dev-server@^2.4.5 but none was installed.
npm WARN bstr-demo@1.0.0 No description
npm WARN bstr-demo@1.0.0 No repository field.
```

Output of npm run watch
```
> bstr-demo@1.0.0 watch /home/geraldo/bstr-demo
> bstr watch

{ Error: spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb',
  path: '/home/geraldo/bstr-demo/node_modules/.bin/bsb',
  spawnargs: [ '-clean-world' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bstr-demo@1.0.0 watch: `bstr watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bstr-demo@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geraldo/.npm/_logs/2017-06-20T11_12_30_004Z-debug.log

```

I don't have code of my own.

Regards,

Geraldo

**Comment by bassjacob** [comment]
Hi @geraldodev,

Sorry this has been difficult. The only way I'm able to reproduce this so far is by not running `npm i` after `./node_modules/.bin/bstr init`.

Just to clarify, are these the exact steps you've run?

```sh
mkdir bstr-demo
cd bstr-demo
npm init -y
npm i -S bassjacob/bstr
./node_modules/.bin/bstr init
npm i # noting the second install here
npm run watch
```
If I copy and paste those commands into a shell directly, it seems to work. Are you running the exact same steps as the above?

**Comment by geraldodev** [comment]
history
```
 4333  cd
 4334  rm -rf bstr-demo
 4335  clear
 4336  mkdir bstr-demo
 4337  cd bstr-demo
 4338  npm init -y
 4339  npm i -S bassjacob/bstr
 4340  ./node_modules/.bin/bstr init
 4341  npm i
 4342  npm run watch
```

{ Error: spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/geraldo/bstr-demo/node_modules/.bin/bsb',
  path: '/home/geraldo/bstr-demo/node_modules/.bin/bsb',
  spawnargs: [ '-clean-world' ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bstr-demo@1.0.0 watch: `bstr watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bstr-demo@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geraldo/.npm/_logs/2017-06-20T11_40_12_653Z-debug.log

**Comment by bassjacob** [comment]
Oh man, I'm sorry. I didn't see your versions above. So the issue is npm@5 creates the package-lock.json file when you first run npm i. then the second npm i will not add any new files. Can you try:

```sh
mkdir bstr-demo
cd bstr-demo
npm init -y
npm i -S bassjacob/bstr
rm package-lock.json # this is the new step
./node_modules/.bin/bstr init
npm i
npm run watch
```
and see if this works now?

**Comment by geraldodev** [comment]
The previous example was on a fresh bstr-demo. I did rm -rf bstr-demo

**Comment by geraldodev** [comment]
Now I see, the package-lock comes from you.

The npm run watch  is working :)

Thanks !

**Comment by bassjacob** [comment]
Haha, excellent! Thank you for helping me find this bug. I'll add that step to the readme now.

**Comment by bassjacob** [comment]
I've added the command to the readme with a specific call out to npm>=5.

**Comment by geraldodev** [comment]
Can I use bstr with bucklescript + tea ?

**Comment by bassjacob** [comment]
I haven't tried, but it should support any bucklescript packages. Although I think I read on discord that bucklescript-tea doesn't support server-side rendering out of the box.

Let me know if it works (or if it doesn't) 😄
